sudo: false
language: ruby
cache: bundler
rvm:
  - 2.4.2
install:
  - bundle install
before_script:
  - git config --global user.email "shchoi5480@gmail.com"
  - git config --global user.name "blue32x"
script: bundle exec rake site:deploy --quiet
env:
  global:
    secure: yPqFPHeUC9y/bFPn/kyBs+dd8+DKOyycKoGfN1xpiABzUcG2C1f7OoHTqbg2z+K/3WllZajDenvL6gK8P0DAe9gjH9vUQAd3P3UKHFBhFFtcMUMfIYJCLc583CpLb8zAvdbeY7Dow/VpqYyWiegHvQ+FmQHhms1mkwzRYqbYtuQaKePrWTXxN0IjT7YrzWP4aodkjhILAJ3ozWUN01DqVbmPfhJkYtl9GJ2nrurOIk3Z7zj6xbZx57CxuqWMNlFcUBXIOHti2FyjnJRmm3Ay0z+PvB/g2ZSB/SowAUg9eBxtKQWHw4R4R9+3UnO/EYF9GBcSHbygZu3osOSQ1JmA7iD+Tu99S2xujLbANpntaPxt6SF9CFGPW36poLTs1HwTjo1aG56uu+hPaQ/1i/oFPpaHUxzZfd/ug8EZnCGZmWROw6K8nAbKJkX/FPUNQSpv9TXFl1jQ8H2GcfNvhm1GymjppZeB5uc/hSidxDMjBoAYc5HFfaA+BgK5fBFfXDI/UulWKI1B48+H5qQB/DkMkzTM8qq8ttCUWrS4ev3WcIVIa2M2HO4ggJR33Bx400lBaJx+cnu/4/LhP69N3beGcyjvoMoKTTwr5bc9/ymGErypTgyLNvfcLeAdYH2Q53lBm+CzELN/Lubt5khnQwDULIcuhZfY2aiUU+rKFUyplrw=
branches:
  only:
    - master
