# .travis.yml
sudo: false
language: ruby
cache: bundler
rvm:
  - 2.4.2

install:
  # Install Jekyll and dependencies
  - bundle install

before_script:
  - git config --global user.email "blue32x@naver.com"
  - git config --global user.name "blue32x"

script: bundle exec rake site:deploy --quiet #--trace

env:
  global:
    #20210703 secure git token
    # travis encrypt GITHUB_TOKEN="ssss" -add
    secure: "IEmq2en4K//DQQhfK4R1pAPQ8PV1gtEVyew7qPBrnRSHCwU059g+Mv0glnTDDv03c3ROASvGTzqDeJ4Jx+ReGNOQ7sUod7i6rxgyACNyz92yrHsSUzALY0qAaLSNC2i47nxenYMx5F02VyF6Ih/JT4DFjrBGkawcHGBZMQxVoktVyJpwWL0/ckVtThUCQUIegVDvJOBkUP34SGhkrKJQ7OSyE5dk6+I4pUBd5TG2fDAn66QpzOI7HYCsW9NQMEb7kehnApSdIw9WHTOYrtJL1SVcInVtXfhQ8UlJObXg7epUimqB5fJxq3mj2m7IjcXEOdKTnzw6mnfg4CY+jvAf3B1M+oQDgvTbTCVLPJZs3RDZ58ixG//o7wZH2yruSUlFypJ6LAcqF7LHwkm+5provkOVCPGdvrOb3nXV/JHX/1GcSpG1qVTVYLzpLuXty3y9b8Ro9+oSY5nBp2wd8iu0cPY4x/M3dKof/1VO2Z8qoX6RKQEtpYJJjyL/8jvYZ/cUkz6AW7LSV16ocliRO0uQlwWMKtUJ7MYdH0TQMr+iTOfWV4wHuUs9xsODxpB2DmlJsMYEA+1yxbc6DyZD2p/rPwMid1JXg1Iod0MIsjt6kdk4GzP6b/t/SAI6BrW3IK/3ah52K9pFfbRPQ9XMMnqnCEsxDyHnujgnfhvLADfeX5o="


branches:
  only:
    - master