# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templatjes via {{ site.myvariable }}.

title: SelfMaker
email: blue32x@naver.com
description: Don't be lazy
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jekyllrb
github_username:  blue32x

#avatar
avatar: /assets/img/me.jpg

pagination:
  enabled: true
  per_page: 5
  # limit: 0
  sort_field: "date"
  sort_reverse: true
  #permalink: '/page/:num/'


# Build settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_hightlighter: rouge
  hard_wrap: false
# theme: minima
plugins:
  - jekyll-feed
  - jekyll-paginate-v2


# default variables for post-type page
defaults:
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post
      comment: true


# sass
# ============================================================================
sass:
  sass_dir: _sass
  style: compressed


# exclude none site related files
# ============================================================================
exclude:
  - README.md
  - LICENSE
  - github
  - package.json
  - package-lock.json
  - node_modules


# google analytics
# ============================================================================
# turn it off -> ga: false
ga: false


# disqus
# ============================================================================
# turn it off for all posts -> disqus: false
# turn it off for a particular post -> add `comment: false` to post front matter
disqus: kkninjae

#travis
deploy:
  type: git
  repo: https://__GITHUB_TOKEN__@github.com/kdevkr/kdevkr.github.io.git
  branch: master